arch:
  - aarch64
  - amd64

description: A multi-output ambient sound mixer for Home Assistant
init: false
homeassistant_api: true
services:
  - mqtt:need
map:
  - media:rw
  - config:rw
name: Amniotic
panel_icon: mdi:waveform
slug: amniotic
url: https://fmtr.link/amniotic


ports:
  8080/tcp: 8007
  22/tcp: null

audio: false

options:
  amniotic__stream_url: "http://homeassistant.local:8007"
  amniotic__path_audio: "/media/Amniotic"
  fmtr_dev: false

schema:
  amniotic__stream_url: str
  amniotic__path_audio: str

  amniotic__mqtt__hostname: str?
  amniotic__mqtt__port: str?
  amniotic__mqtt__username: str?
  amniotic__mqtt__password: password?

  fmtr_dev: bool


webui: http://[HOST]:[PORT:8080]/




version: 1.2.4

