arch:
  - aarch64
  - amd64

description: A multi-output ambient sound mixer for Home Assistant
init: false

map:
  - media:rw
  - config:rw
name: Amniotic
panel_icon: mdi:nature-people
slug: amniotic
url: https://fmtr.link/amniotic


ports:
  8007/tcp: 8080

audio: false

options:
  #  amniotic__mqtt__hostname: "mqtt.local"
  #  amniotic__mqtt__port: "1883"
  #  amniotic__mqtt__username: "mqtt_user"
  #  amniotic__mqtt__password: "mqtt_pass"
  amniotic__stream_url: "http://homeassistant.local:8007"
  amniotic__path_audio: "/media/Amniotic"

schema:
  #  amniotic__mqtt__hostname: str
  #  amniotic__mqtt__port: str
  #  amniotic__mqtt__username: str?
  #  amniotic__mqtt__password: str?
  amniotic__stream_url: str
  amniotic__path_audio: str

services:
  - mqtt:need

version: 1.0.13

