arch:
  - aarch64
  - amd64

description: A multi-output ambient sound mixer for Home Assistant
init: false
homeassistant_api: true
services:
  - mqtt:need
map:
  - media:rw
  - config:rw
name: Amniotic
panel_icon: mdi:nature-people
slug: amniotic
url: https://fmtr.link/amniotic


ports:
  8080/tcp: 8007
  22/tcp: 2207

audio: false

options:
  #  amniotic__mqtt__hostname: "mqtt.local"
  #  amniotic__mqtt__port: "1883"
  #  amniotic__mqtt__username: "mqtt_user"
  #  amniotic__mqtt__password: "mqtt_pass"
  amniotic__stream_url: "http://homeassistant.local:8007"
  amniotic__path_audio: "/media/Amniotic"
  is_ssh: false

schema:
  #  amniotic__mqtt__hostname: str
  #  amniotic__mqtt__port: str
  #  amniotic__mqtt__username: str?
  #  amniotic__mqtt__password: str?
  amniotic__stream_url: str
  amniotic__path_audio: str
  is_ssh: bool


webui: http://[HOST]:[PORT:8080]/




version: 1.0.22

